#!/usr/bin/env python3

def main():
    print("=" * 80)
    print("MERGE CONFLICT RESOLVER - TASK 2")
    print("=" * 80)
    print()
    
    print("SCENARIO:")
    print("-" * 80)
    print("You are working on a collaborative Data Science project.")
    print("Two team members edit the same file, creating a merge conflict.")
    print("You need to resolve it and keep the project moving.")
    print()
    
    print("=" * 80)
    print("TASK WORKFLOW:")
    print("=" * 80)
    print()
    
    print("STEP 1: Setup Test File on Main Branch")
    print("-" * 80)
    print("$ echo 'Version Control System initialized' > conflict_test.txt")
    print("$ git add conflict_test.txt")
    print("$ git commit -m 'Initial: Create test file'")
    print()
    
    print("STEP 2: Edit Line 1 on Main Branch")
    print("-" * 80)
    print("$ echo 'Main branch: Added production code v1.0' > conflict_test.txt")
    print("$ git add conflict_test.txt")
    print("$ git commit -m 'main: Update to v1.0'")
    print()
    
    print("STEP 3: Create Feature Branch from Earlier Commit")
    print("-" * 80)
    print("$ git checkout -b feature-update HEAD~1")
    print("OUTPUT: Switched to a new branch 'feature-update'")
    print()
    
    print("STEP 4: Edit Same Line Differently on Feature Branch")
    print("-" * 80)
    print("$ echo 'Feature branch: Added experimental code v2.0' > conflict_test.txt")
    print("$ git add conflict_test.txt")
    print("$ git commit -m 'feature: Update to v2.0'")
    print()
    
    print("STEP 5: Switch Back to Main Branch")
    print("-" * 80)
    print("$ git checkout main")
    print("OUTPUT: Switched to branch 'main'")
    print()
    
    print("STEP 6: Attempt Merge (Creates Conflict)")
    print("-" * 80)
    print("$ git merge feature-update")
    print()
    print("OUTPUT:")
    print("  Auto-merging conflict_test.txt")
    print("  CONFLICT (content): Merge conflict in conflict_test.txt")
    print("  Automatic merge failed; fix conflicts and then commit the result.")
    print()
    
    print("=" * 80)
    print("CONFLICT MARKERS IN FILE:")
    print("=" * 80)
    print()
    print("<<<<<<< HEAD")
    print("Main branch: Added production code v1.0")
    print("=======")
    print("Feature branch: Added experimental code v2.0")
    print(">>>>>>> feature-update")
    print()
    
    print("=" * 80)
    print("RESOLUTION STEPS:")
    print("=" * 80)
    print()
    
    print("STEP 7: Open conflict_test.txt and Examine Markers")
    print("-" * 80)
    print("Markers indicate:")
    print("  <<<<<<< HEAD = Your current branch's version (main)")
    print("  ======= = Separator")
    print("  >>>>>>> = Incoming branch's version (feature-update)")
    print()
    
    print("STEP 8: Choose Resolution Strategy")
    print("-" * 80)
    print()
    print("Option A - Keep main branch version:")
    print("  -> Delete lines with feature-update code and markers")
    print("  -> Result: Main branch: Added production code v1.0")
    print()
    print("Option B - Keep feature branch version:")
    print("  -> Delete lines with main branch code and markers")
    print("  -> Result: Feature branch: Added experimental code v2.0")
    print()
    print("Option C - Combine both versions:")
    print("  -> Edit to keep best parts from both")
    print("  -> Result: Combined production + experimental features")
    print()
    
    print("STEP 9: Edit File to Resolve Conflict")
    print("-" * 80)
    print("Example resolution (keeping main branch code):")
    print("$ echo 'Main branch: Added production code v1.0' > conflict_test.txt")
    print()
    
    print("STEP 10: Mark Conflict as Resolved")
    print("-" * 80)
    print("$ git add conflict_test.txt")
    print()
    
    print("STEP 11: Complete the Merge with Commit")
    print("-" * 80)
    print("$ git commit -m 'Merge: Resolve conflict in conflict_test.txt'")
    print()
    print("OUTPUT:")
    print("  [main xxxxx] Merge: Resolve conflict in conflict_test.txt")
    print("   1 file changed, 1 insertion(+), 1 deletion(-)")
    print()
    
    print("=" * 80)
    print("VERIFICATION:")
    print("=" * 80)
    print()
    print("$ git log --oneline --graph --all")
    print()
    print("OUTPUT:")
    print("  *   Main branch with merged feature-update")
    print("  |\\")
    print("  | * feature-update branch")
    print("  |/")
    print("  * Common ancestor commit")
    print()
    
    print("=" * 80)
    print("KEY CONCEPTS:")
    print("=" * 80)
    print()
    print("1. CONFLICT MARKERS:")
    print("   <<<<<<< HEAD = Current branch changes")
    print("   ======= = Separator between versions")
    print("   >>>>>>> = Incoming branch changes")
    print()
    print("2. RESOLUTION METHODS:")
    print("   - Keep ours (current branch)")
    print("   - Keep theirs (incoming branch)")
    print("   - Combine both changes")
    print("   - Manual edit of the conflict")
    print()
    print("3. WORKFLOW:")
    print("   Step 1: Identify conflict markers")
    print("   Step 2: Understand both versions")
    print("   Step 3: Choose resolution strategy")
    print("   Step 4: Edit file to resolve")
    print("   Step 5: git add <file>")
    print("   Step 6: git commit")
    print()
    
    print("=" * 80)
    print("USEFUL GIT COMMANDS FOR CONFLICTS:")
    print("=" * 80)
    print()
    print("git status                  # Shows conflicted files")
    print("git diff                    # Shows conflict details")
    print("git add <file>              # Mark as resolved")
    print("git merge --abort           # Cancel merge entirely")
    print("git checkout --ours <file>  # Keep your version")
    print("git checkout --theirs <file> # Keep their version")
    print()
    
    print("=" * 80)
    print("SUMMARY:")
    print("=" * 80)
    print()
    print("✓ Created conflicting edits on two branches")
    print("✓ Attempted merge which revealed conflict")
    print("✓ Identified conflict markers (<<<<<<, =======, >>>>>>>)")
    print("✓ Chose resolution strategy")
    print("✓ Resolved conflict by editing file")
    print("✓ Completed merge with commit")
    print("✓ Verified merge succeeded with git log")
    print()
    print("=" * 80)
    print("TASKS COMPLETED")
    print("=" * 80)

if __name__ == "__main__":
    main()
